### ISSUE TITLE
call to ESMF_ConfigSetAttribute overwrites the next line in config (ESMF_Config)

### ISSUE THREAD

**Issue by metdyn** [GEOS-ESM/MAPL#2385]
I met with an unexpected outcome when calling ESMF_ConfigSetAttribute  to modify an entry in config.  The code below with the input shows it overwrites the next line in the config. 

```
 MAPL_EpochSwathMod.F90
        function create_grid()
          188 │ │ call ESMF_ConfigSetAttribute( config_grid, trim(time_string), label=trim(key)//'.Epoch_init:', _RC)
```
config:
```
  SwathGrid.Epoch_init:  '20121113T000000'
  SwathGrid.nc_Time:       'time'
  SwathGrid.nc_Longitude:   'cell_across_swath'
```

      call ESMF_ConfigFindLabel(config, 'SwathGrid.nc_Time:', isPresent=ispresent, rc=status)
      print*, 'SwathGrid.nc_Time: ispresent=', ispresent
shows:
 SwathGrid.nc_Time: ispresent= F

Moving `SwathGrid.Epoch_init:  '20121113T000000'` to the end of the segment solves the problem.  I am documenting this as a future reference.

**Comment by mathomp4** [comment]
Hmm. Maybe something we want to bring to ESMF's attention?

**Comment by metdyn** [comment]
Hi @darianboggs,

I find this bug when in ExtDataDriver.x using nag and gcc.  
However I suspect this can be reproduced using ESMF only. (I suspect it is directly related to ESMF)

For example, given a three-line config file:
A: 1
B: 2
C: 3

We read the config into memory from  ESMF
modify the entry `A: 1`  to `A: 11` by calling ESMF_ConfigSetAttribute( config, trim(string), label='A', _RC)

check if the nextline in the config (`B: 2`) is still there. 

Thanks.

**Comment by darianboggs** [comment]
**DO NOT MERGE `bugfix/wdboggs/#2385-overwrite_ESMF_ConfigSetAttribute`**.

Branch `bugfix/wdboggs/#2385-overwrite_ESMF_ConfigSetAttribute` implements the standalone app, `OverwriteConfig.x`, to test this bug.

`OverwriteConfig.x` recreates the error with the Intel compiler. @mathomp4 or @tclune may want to try compiling with NAG. `make install` will create the standalone recreator from `Apps/OverwriteConfig.F90`. `OverwriteConfig.x` requires no arguments, but you can supply a temp file name as the first argument. The temp file will be deleted on completion.

**DO NOT MERGE `bugfix/wdboggs/#2385-overwrite_ESMF_ConfigSetAttribute`**.

The branch not been tested for any other purpose.

**Comment by mathomp4** [comment]
@darianboggs So how did you call your code and what should we look for when running it (aka, what is the "wrong" behavior)?

**Comment by mathomp4** [comment]
Well, with GNU on Alderaan I get:
```
❯ ./OverwriteConfig.x
 temporary file: overwrite_20231017135938.710_rc.tmp
 Error closing overwrite_20231017135938.710_rc.tmp. Manually delete if necessary.
Result - Failure: test_overwrite failed: :: ESMF_ConfigCreate successful :: write_attributes successful :: ESMF_ConfigLoadFile successful
```
Is there a "verbose" way to see what's happening? Lots of successfuls, but result is a Failure...

**Comment by darianboggs** [comment]
I pushed up simpler tests, and `SimpleOverwriteConfig.x` is now passing, finding the second attribute label. I am looking at the difference between `SimpleOverwriteConfig.F90` and `OverwriteConfig_FullTest.F90` to see why the simpler version passes, but the original version fails like Yonggang's code.

**Comment by tclune** [comment]
Often one must start with the large failing case and whittle tiny bits and verify it still fails.  And if your not careful, it is a good idea to save intermediates so that if you trip you don't have to start over.

**Comment by metdyn** [comment]
@darianboggs, Thanks. I agree with most of what you find, except 4, which I have not seen before.  I didnot know about `MAPL_ConfigSetAttribute` before. Maybe if I replace `ESMF_ConfigSetAttribute`  with `MAPL_ConfigSetAttribute`, this problem will not occur.

**Comment by tclune** [comment]
At this point we are not trying to find a workaround.  We _want_ to demonstrate a clear error so that it can be repaired.   So if changing from ESMF set to MAPL set appears to solve the problem, please use the former to create a reproducer.   Again, at this point, even if it involves an entire build/run of GEOS that is acceptable.   We can whittle it down from there.

**Comment by mathomp4** [comment]
I'll comment to keep open. I think this is in ESMF's hands now...right?

**Comment by metdyn** [comment]
Thank you for keeping this thread alive, @mathomp4.   That is right.

**Comment by mathomp4** [comment]
I'm not sure the status of this. I want to say ESMF got a reproducer? But I'm not sure.
