### ISSUE TITLE
Bug(s) in Test_ComponentSpecParser

### ISSUE THREAD

**Issue by tclune** [GEOS-ESM/MAPL#3248]
Building with NAG reveals compilation and fixes of those reveal run-time bugs and fixing those reveals failing tests.

1. Integer declared with ESMF_KIND_**R**4  (Should be **I**4)
   - Not surprising this works with Intel and GNU which have R4=I4=4.  NAG does not.
2. expected_timestring and actual_timestring are declared allocatable but not allocated.  ESMF expects allocated strings (unfortunately)
   - I do not know why this ran successfully with Intel & GNU in the CI.   Clear runtime error message from NAG.
3. Fixing the strings results in a failing tests
```
Failure
 in: 
Test_MaxAction_suite.test_max_accumulate_R4
  Location: 
[Test_MaxAction.pf:39]
accumulated_field not equal to expected values
Arrays not conformable failure:
    Expected shape: [4]
      Actual shape: [16]
  
Failure
 in: 
Test_MinAction_suite.test_min_accumulate_R4
  Location: 
[Test_MinAction.pf:39]
accumulated_field not equal to expected values
Arrays not conformable failure:
    Expected shape: [4]
      Actual shape: [16]
  
 FAILURES!!!
Tests run: 219, Failures: 2, Errors: 0
, Disabled: 0
```

**Comment by darianboggs** [comment]
This may be related to MPI. The generic3g tests pass when compiled by NAG on bucy. The tests for the accumulator have no "npes" parameter.

**Comment by tclune** [comment]
@darianboggs  - Just want to make sure I understand.   You fixed (1) and (2) and then found the tests ran without error on bucy?   Weird.  Very consistently failing on my laptop with the message above.

**Comment by darianboggs** [comment]
Yes. Now that I added npes, it produces the error that you saw. I verified in the test I ran yesterday that it did not fail on bucy with NAG.

**Comment by darianboggs** [comment]
It appears that fixes for (1) and (2) are in `release/MAPL-v3' already. In my bugfix branch, I removed the expected_timestring and actual_timestring. They aren't needed for the test. I used them to make an error message string, but now that the test is working, the message is not needed. I replaced the error message with a simple message.

Nonetheless, I'll leave well enough alone regarding (2), and I won't push up my fix for (1) and (2).

**Comment by darianboggs** [comment]
Fixed by #3276

**Comment by darianboggs** [comment]
Closing

**Comment by tclune** [comment]
I think I still see the issue. I will reopen next week depending on what I see.
